INFO: loading config from shadowsock/shadowsocks.json
Traceback (most recent call last):
  File "/home/linyimin/.local/bin/sslocal", line 11, in <module>
    sys.exit(main())
  File "/home/linyimin/.local/lib/python2.7/site-packages/shadowsocks/local.py", line 39, in main
    config = shell.get_config(True)
  File "/home/linyimin/.local/lib/python2.7/site-packages/shadowsocks/shell.py", line 149, in get_config
    with open(config_path, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'shadowsock/shadowsocks.json'
